### PR TITLE
revert healpix workaround

### PR DESCRIPTION
**Pull request by sroet**
Revert #188

### CODE REVIEW

**Review by McHaillet — APPROVED** [review]
LGTM!

**Comment by McHaillet** [comment]
Should this update our deps and version number?

**Comment by sroet** [comment]
> Should this update our deps and version number?

Not sure what you mean by 'deps'?
version number should be fine as nothing changed in our code

**Comment by McHaillet** [comment]
> > Should this update our deps and version number?
> 
> Not sure what you mean by 'deps'? version number should be fine as nothing changed in our code

I meant the dependencies so that we only rely on healpix 2024.2

**Comment by sroet** [comment]
> > > Should this update our deps and version number?
> > 
> > Not sure what you mean by 'deps'? version number should be fine as nothing changed in our code
> 
> I meant the dependencies so that we only rely on healpix 2024.2 

Nah, any new install should pull the new version. And the old version still works well as long as you downgrade numpy to 1.x

**Comment by McHaillet** [comment]
Okay!

**Pull request merged**
