### PR TITLE
pre-commit with ruff

### PR DESCRIPTION
**Pull request by McHaillet**
PR for pre-commits.

to-do:
- [x] add pre-commit config
- [x] update .toml dev dependencies
- [x] run whole codebase through ruff check and ruff format
- [x] add ruff checks to test pipline

### CODE REVIEW

**Comment by sroet** [comment]
can I also propose adding a test that checks ruff before running the tests?

**Comment by McHaillet** [comment]
@sroet I am also fine if you continue work on this PR (if you have time of course). I don't know how easy it is to take over a PR, or maybe its easier to merge this first and make a new PR?

**Comment by sroet** [comment]
>  I don't know how easy it is to take over a PR, or maybe its easier to merge this first and make a new PR?

Looks like I can just push to this branch 😄 

In the last commit I added a catch-all `[all]` so that we don't have to keep updating our docs if we decide to add more optional dependencies down the line

**Comment by McHaillet** [comment]
> Looks like I can just push to this branch 😄

Noice 👍 
 
> In the last commit I added a catch-all `[all]` so that we don't have to keep updating our docs if we decide to add more optional dependencies down the line

Good one

**Comment by sroet** [comment]
@McHaillet I think this is ready 😄 please have a look

**Comment by McHaillet** [comment]
Got it. The pipeline addition just checks if everything is formatted/linted, right?

**Comment by McHaillet** [comment]
Good!

I checked the config and setup files, and looks good. I assume all the python files are auto formatted. The tests pass, so seems good from my side.

**Review by sroet — APPROVED** [review]

**Pull request merged**
