### PR TITLE
Get tutorial-tests.yml working

### LINKED ISSUE #148: Test the tutorial
We should walk through the tutorial code.
A command to pull a zip file with the 4 files for a single tomogram is:
`curl -L -O -J -H "X-Dataverse-key:$DATAVERSE_API_TOKEN" https://dataverse.nl/api/access/datafiles/384731,384724,384706,384718`

This should only run on our main branch and should probably be part of the weekly as it needs access to the repository secrets for the API token

Another option is to instead use [git lfs](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage) to store the single tomogram mrc (especially since we are now pip installable that don't package the tests anyway). This would also allow us to tests the entry points properly  and generate coverage data on the PRs for them

### PR DESCRIPTION
**Pull request by sroet**
Alright, I am rerunning this job only on this branch until I get it working

closes #148

### CODE REVIEW

**Comment by sroet** [comment]
@McHaillet This finally works! It runs in 101 min, and can be seen here: https://github.com/SBC-Utrecht/pytom-match-pick/actions/runs/10425169098/job/28875465809 (commit 4ba5eda, which failed on ruff stuff in the regular unitests)

With that runtime, it might be worthwhile to actually pip install cupy, what do you think?

**Comment by sroet** [comment]
It also already found the first error in the tutorial :sweat_smile:

**Review by McHaillet — APPROVED** [review]
LGTM

**Comment by McHaillet** [comment]
> It also already found the first error in the tutorial 😅

Nice! What was the error?

**Comment by sroet** [comment]
> > It also already found the first error in the tutorial 😅
> 
> Nice! What was the error?

the file you get from emdb is called  `emd_2938.map` instead of `emd_2938.mrc` (was mentioned that way in the file structure)

**Pull request merged**
