### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sroet**
Fix a broken link and hide the mkdoc comment stuff

### CODE REVIEW

**Comment by sroet** [comment]
@McHaillet please make sure the docs can still be build with this alteration (to hide the mkdocs comments on github itself)

**Comment by sroet** [comment]
closed as duplicate of #201

**Comment by sroet** [comment]
reopened as this style of markdown comment works better than the one in #201

**Review by McHaillet — APPROVED** [review]
LGTM

**Pull request merged**
